### PR TITLE
Added backend for Google Scholar

### PR DESCRIPTION
**Pull request by nchodosh**
I added a few functions to make a backend for Google Scholar out of this [similar package](https://github.com/cute-jumper/gscholar-bibtex)

### CODE REVIEW

**Comment by nchodosh** [comment]
The tests fail because it depends on the other project which isn't installed. Would it be better to just take everything needed from that repo to remove the dependency?

**Comment by cpitclaudel** [comment]
This looks great! Sorry for the delay.

Taking the dependency out would be better if we include this in core, but another good approach might be to publish this as a separate plugin on melpa; biblio was built to be extensible, so it would be completely fine to publish a biblio-gscholar package to MELPA and make that depend on gscholar-bibtex.

What do you think?

**Comment by nchodosh** [comment]
Sorry for the delay on my end! Yes that sounds great, it might take a a bit since I've never published anything on MELPA before. Once that's done could you add a note to the README of this project to let people know that it exists?

**Comment by cpitclaudel** [comment]
> Once that's done could you add a note to the README of this project to let people know that it exists?

Yes, absolutely

**Comment by nchodosh** [comment]
Would you mind testing the extension on your end? I was working on it and it seems that Google has upped their anti-scraping game and it's refusing to load the results without javascript. Some python scrapers I downloaded seem to be having the same problem.

**Comment by nchodosh** [comment]
Would you mind testing the extension on your end? I was working on it and it seems that Google has upped their anti-scraping game and it's refusing to load the results without javascript. Some python scrapers I downloaded seem to be having the same problem.

**Comment by cpitclaudel** [comment]
Sorry for the delay. As I said, I think it would be ideal to have this as a separate MELPA package, since it depends on non-trivial Google Scholar parsing. I'll be happy to link to it from the README once it's ready ^^

**Comment by seanfarley** [comment]
> Sorry for the delay. As I said, I think it would be ideal to have this as a separate MELPA package, since it depends on non-trivial Google Scholar parsing. I'll be happy to link to it from the README once it's ready ^^

I was in need of this functionality so I went ahead and made it into a package here: https://github.com/seanfarley/biblio-gscholar.el

@nchodosh, if you like, please feel free to take ownership of the repo I created. I'm not sure about what copyright to assign it, by the way, which means I'm not sure if it can be submitted to melpa as-is. Anyways, hope this helps others.

**Pull request closed without merging**
